//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCD.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCD.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collapse_hightlight {
            get {
                object obj = ResourceManager.GetObject("collapse_hightlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownMouse {
            get {
                object obj = ResourceManager.GetObject("DownMouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expand {
            get {
                object obj = ResourceManager.GetObject("expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expand_highlight {
            get {
                object obj = ResourceManager.GetObject("expand_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_Bankre负责人工作统计报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_Bankre负责人工作统计报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_CS数据变更报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_CS数据变更报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_Excel分解 {
            get {
                object obj = ResourceManager.GetObject("menu_br_Excel分解", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_Master_Store报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_Master_Store报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_代理信息 {
            get {
                object obj = ResourceManager.GetObject("menu_br_代理信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_任务管理 {
            get {
                object obj = ResourceManager.GetObject("menu_br_任务管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_余额信息报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_余额信息报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_关于 {
            get {
                object obj = ResourceManager.GetObject("menu_br_关于", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_凭证号回写 {
            get {
                object obj = ResourceManager.GetObject("menu_br_凭证号回写", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_凭证号回写异常报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_凭证号回写异常报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_历史任务 {
            get {
                object obj = ResourceManager.GetObject("menu_br_历史任务", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_历史计划报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_历史计划报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_取消月结 {
            get {
                object obj = ResourceManager.GetObject("menu_br_取消月结", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_基础数据 {
            get {
                object obj = ResourceManager.GetObject("menu_br_基础数据", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_存款超期原因录入 {
            get {
                object obj = ResourceManager.GetObject("menu_br_存款超期原因录入", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_存款超期天数设置 {
            get {
                object obj = ResourceManager.GetObject("menu_br_存款超期天数设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_存款超期报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_存款超期报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_密码修改 {
            get {
                object obj = ResourceManager.GetObject("menu_br_密码修改", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_对账Deadline设置 {
            get {
                object obj = ResourceManager.GetObject("menu_br_对账Deadline设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_对账超期天数设置 {
            get {
                object obj = ResourceManager.GetObject("menu_br_对账超期天数设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_工作日设置 {
            get {
                object obj = ResourceManager.GetObject("menu_br_工作日设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_已删除用户报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_已删除用户报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_已配对信息报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_已配对信息报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_帮助 {
            get {
                object obj = ResourceManager.GetObject("menu_br_帮助", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_待处理任务 {
            get {
                object obj = ResourceManager.GetObject("menu_br_待处理任务", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_报表管理 {
            get {
                object obj = ResourceManager.GetObject("menu_br_报表管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_拒绝原因明细报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_拒绝原因明细报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_拒绝率统计报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_拒绝率统计报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_拒绝类型设置 {
            get {
                object obj = ResourceManager.GetObject("menu_br_拒绝类型设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_拒绝统计报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_拒绝统计报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_挂账数据汇总报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_挂账数据汇总报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_操作手册 {
            get {
                object obj = ResourceManager.GetObject("menu_br_操作手册", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_数据同步 {
            get {
                object obj = ResourceManager.GetObject("menu_br_数据同步", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_文档管理 {
            get {
                object obj = ResourceManager.GetObject("menu_br_文档管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_权限设置 {
            get {
                object obj = ResourceManager.GetObject("menu_br_权限设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_用户操作日志报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_用户操作日志报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_用户管理 {
            get {
                object obj = ResourceManager.GetObject("menu_br_用户管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_用户组权限报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_用户组权限报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_用户组设置 {
            get {
                object obj = ResourceManager.GetObject("menu_br_用户组设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_科目对账状态报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_科目对账状态报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_科目异常原因录入 {
            get {
                object obj = ResourceManager.GetObject("menu_br_科目异常原因录入", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_租金计算 {
            get {
                object obj = ResourceManager.GetObject("menu_br_租金计算", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_系统管理 {
            get {
                object obj = ResourceManager.GetObject("menu_br_系统管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_统计报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_统计报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_记录报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_记录报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_账务处理 {
            get {
                object obj = ResourceManager.GetObject("menu_br_账务处理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_超期率统计报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_超期率统计报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_超期统计报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_超期统计报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_银行科目异常报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_银行科目异常报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_银行科目报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_银行科目报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_银行科目比例设置 {
            get {
                object obj = ResourceManager.GetObject("menu_br_银行科目比例设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_银行科目设置 {
            get {
                object obj = ResourceManager.GetObject("menu_br_银行科目设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_银行账单记录报表 {
            get {
                object obj = ResourceManager.GetObject("menu_br_银行账单记录报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_预测租金计算 {
            get {
                object obj = ResourceManager.GetObject("menu_br_预测租金计算", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_br_预测销售数据 {
            get {
                object obj = ResourceManager.GetObject("menu_br_预测销售数据", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_AP计算总额报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_AP计算总额报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_English {
            get {
                object obj = ResourceManager.GetObject("menu_rl_English", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_GL计算异常报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_GL计算异常报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_GL计算总额报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_GL计算总额报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_GL计算日期设置 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_GL计算日期设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_Kiosk调整记录报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_Kiosk调整记录报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_REJECT类型 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_REJECT类型", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_TypeCode信息 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_TypeCode信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_事项列表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_事项列表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_事项导入 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_事项导入", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_事项类型 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_事项类型", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_代理信息 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_代理信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_任务状态报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_任务状态报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_任务管理 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_任务管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_供应商信息 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_供应商信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_修改记录报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_修改记录报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_公司信息 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_公司信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_关于 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_关于", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_关帐 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_关帐", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_关帐管理 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_关帐管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_区域信息 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_区域信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_合同到期预警报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_合同到期预警报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_合同导入 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_合同导入", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_合同管理 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_合同管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_同步计划设置 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_同步计划设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_基本信息 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_基本信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_实体类型 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_实体类型", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_密码修改 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_密码修改", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_工作分配报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_工作分配报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_工作日设置 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_工作日设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_已删除用户报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_已删除用户报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_已处理任务 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_已处理任务", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_帮助 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_帮助", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_平均租金对比报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_平均租金对比报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_年度对比报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_年度对比报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_待办任务 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_待办任务", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_报表管理 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_报表管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_拒绝任务数统计报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_拒绝任务数统计报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_拒绝明细报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_拒绝明细报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_拒绝率统计报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_拒绝率统计报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_新增事项 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_新增事项", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_权限报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_权限报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_权限设置 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_权限设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_模块设置 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_模块设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_甜品店挂靠关系变更报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_甜品店挂靠关系变更报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_甜品站信息 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_甜品站信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_用户信息 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_用户信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_用户信息操作日志报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_用户信息操作日志报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_用户区域权限设置 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_用户区域权限设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_用户组权限设置 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_用户组权限设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_用户组设置 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_用户组设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_科目信息 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_科目信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_租赁事项记录 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_租赁事项记录", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_租金计算报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_租金计算报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_简体中文 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_简体中文", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_系统参数 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_系统参数", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_系统设置 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_系统设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_繁体中文 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_繁体中文", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_语言 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_语言", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_超时任务报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_超时任务报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_超时率统计报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_超时率统计报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_部门信息 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_部门信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_销售数据报表 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_销售数据报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_预测销售数据导入 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_预测销售数据导入", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_预测销售数据录入 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_预测销售数据录入", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_rl_餐厅信息 {
            get {
                object obj = ResourceManager.GetObject("menu_rl_餐厅信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Move_First {
            get {
                object obj = ResourceManager.GetObject("Move_First", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Move_Last {
            get {
                object obj = ResourceManager.GetObject("Move_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Move_Next {
            get {
                object obj = ResourceManager.GetObject("Move_Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Move_Previous {
            get {
                object obj = ResourceManager.GetObject("Move_Previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpMouse {
            get {
                object obj = ResourceManager.GetObject("UpMouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
