//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCD.RLPlanning.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCD.RLPlanning.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap con_change {
            get {
                object obj = ResourceManager.GetObject("con_change", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap con_copy {
            get {
                object obj = ResourceManager.GetObject("con_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap con_view {
            get {
                object obj = ResourceManager.GetObject("con_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_file_doc {
            get {
                object obj = ResourceManager.GetObject("icon_file_doc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_file_gif {
            get {
                object obj = ResourceManager.GetObject("icon_file_gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_file_jpg {
            get {
                object obj = ResourceManager.GetObject("icon_file_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_file_pdf {
            get {
                object obj = ResourceManager.GetObject("icon_file_pdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_file_ppt {
            get {
                object obj = ResourceManager.GetObject("icon_file_ppt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_file_txt {
            get {
                object obj = ResourceManager.GetObject("icon_file_txt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_file_unknow {
            get {
                object obj = ResourceManager.GetObject("icon_file_unknow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_file_xls {
            get {
                object obj = ResourceManager.GetObject("icon_file_xls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Junk {
            get {
                object obj = ResourceManager.GetObject("Junk", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon LOGO1 {
            get {
                object obj = ResourceManager.GetObject("LOGO1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon LOGO2 {
            get {
                object obj = ResourceManager.GetObject("LOGO2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon LOGO3 {
            get {
                object obj = ResourceManager.GetObject("LOGO3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon LOGO4 {
            get {
                object obj = ResourceManager.GetObject("LOGO4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_REJECT类型 {
            get {
                object obj = ResourceManager.GetObject("menu_REJECT类型", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_TypeCode信息 {
            get {
                object obj = ResourceManager.GetObject("menu_TypeCode信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_业主信息 {
            get {
                object obj = ResourceManager.GetObject("menu_业主信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_事项Reject报表 {
            get {
                object obj = ResourceManager.GetObject("menu_事项Reject报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_事项列表 {
            get {
                object obj = ResourceManager.GetObject("menu_事项列表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_事项导入 {
            get {
                object obj = ResourceManager.GetObject("menu_事项导入", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_事项类型 {
            get {
                object obj = ResourceManager.GetObject("menu_事项类型", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_代理信息 {
            get {
                object obj = ResourceManager.GetObject("menu_代理信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_任务管理 {
            get {
                object obj = ResourceManager.GetObject("menu_任务管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_公司信息 {
            get {
                object obj = ResourceManager.GetObject("menu_公司信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_关于 {
            get {
                object obj = ResourceManager.GetObject("menu_关于", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_区域信息 {
            get {
                object obj = ResourceManager.GetObject("menu_区域信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_合同管理 {
            get {
                object obj = ResourceManager.GetObject("menu_合同管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_基本信息 {
            get {
                object obj = ResourceManager.GetObject("menu_基本信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_实体类型 {
            get {
                object obj = ResourceManager.GetObject("menu_实体类型", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_密码修改 {
            get {
                object obj = ResourceManager.GetObject("menu_密码修改", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_工作日设置 {
            get {
                object obj = ResourceManager.GetObject("menu_工作日设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_已删除用户报表 {
            get {
                object obj = ResourceManager.GetObject("menu_已删除用户报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_已办任务 {
            get {
                object obj = ResourceManager.GetObject("menu_已办任务", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_帮助 {
            get {
                object obj = ResourceManager.GetObject("menu_帮助", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_待处理任 {
            get {
                object obj = ResourceManager.GetObject("menu_待处理任", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_报表管理 {
            get {
                object obj = ResourceManager.GetObject("menu_报表管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_新增事项 {
            get {
                object obj = ResourceManager.GetObject("menu_新增事项", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_未设置CheckList餐厅报表 {
            get {
                object obj = ResourceManager.GetObject("menu_未设置CheckList餐厅报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_权限设置 {
            get {
                object obj = ResourceManager.GetObject("menu_权限设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_模块设置 {
            get {
                object obj = ResourceManager.GetObject("menu_模块设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_甜品站信息 {
            get {
                object obj = ResourceManager.GetObject("menu_甜品站信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_用户Reject报表 {
            get {
                object obj = ResourceManager.GetObject("menu_用户Reject报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_用户信息 {
            get {
                object obj = ResourceManager.GetObject("menu_用户信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_用户操作日志报表 {
            get {
                object obj = ResourceManager.GetObject("menu_用户操作日志报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_用户组设置 {
            get {
                object obj = ResourceManager.GetObject("menu_用户组设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_科目信息 {
            get {
                object obj = ResourceManager.GetObject("menu_科目信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_租赁事项记录 {
            get {
                object obj = ResourceManager.GetObject("menu_租赁事项记录", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_简体中文 {
            get {
                object obj = ResourceManager.GetObject("menu_简体中文", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_系统参数设置 {
            get {
                object obj = ResourceManager.GetObject("menu_系统参数设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_系统管理 {
            get {
                object obj = ResourceManager.GetObject("menu_系统管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_繁体中文 {
            get {
                object obj = ResourceManager.GetObject("menu_繁体中文", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_英语 {
            get {
                object obj = ResourceManager.GetObject("menu_英语", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_计算日期设置 {
            get {
                object obj = ResourceManager.GetObject("menu_计算日期设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_语言 {
            get {
                object obj = ResourceManager.GetObject("menu_语言", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_跟进事项报表 {
            get {
                object obj = ResourceManager.GetObject("menu_跟进事项报表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_部门信息 {
            get {
                object obj = ResourceManager.GetObject("menu_部门信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_餐厅信息 {
            get {
                object obj = ResourceManager.GetObject("menu_餐厅信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_Hover {
            get {
                object obj = ResourceManager.GetObject("Stop_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UploadSource {
            get {
                object obj = ResourceManager.GetObject("UploadSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UploadTo {
            get {
                object obj = ResourceManager.GetObject("UploadTo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UploadTransfer {
            get {
                object obj = ResourceManager.GetObject("UploadTransfer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 保存 {
            get {
                object obj = ResourceManager.GetObject("保存", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 关闭 {
            get {
                object obj = ResourceManager.GetObject("关闭", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 删除 {
            get {
                object obj = ResourceManager.GetObject("删除", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 复制 {
            get {
                object obj = ResourceManager.GetObject("复制", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 导出数据 {
            get {
                object obj = ResourceManager.GetObject("导出数据", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 已启用 {
            get {
                object obj = ResourceManager.GetObject("已启用", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 已禁用 {
            get {
                object obj = ResourceManager.GetObject("已禁用", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 打印 {
            get {
                object obj = ResourceManager.GetObject("打印", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 打印预览 {
            get {
                object obj = ResourceManager.GetObject("打印预览", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 批量复制 {
            get {
                object obj = ResourceManager.GetObject("批量复制", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 撤消 {
            get {
                object obj = ResourceManager.GetObject("撤消", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 新建 {
            get {
                object obj = ResourceManager.GetObject("新建", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 查看已删除 {
            get {
                object obj = ResourceManager.GetObject("查看已删除", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 查询 {
            get {
                object obj = ResourceManager.GetObject("查询", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 注销 {
            get {
                object obj = ResourceManager.GetObject("注销", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 编辑 {
            get {
                object obj = ResourceManager.GetObject("编辑", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 设置代理 {
            get {
                object obj = ResourceManager.GetObject("设置代理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 读取 {
            get {
                object obj = ResourceManager.GetObject("读取", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
