//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCD.RLPlanning.Client.UUPPopedomService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UUPPopedomService.IPopedomService")]
    public interface IPopedomService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopedomService/GetUserPopedomByUserName", ReplyAction="http://tempuri.org/IPopedomService/GetUserPopedomByUserNameResponse")]
        System.Data.DataTable GetUserPopedomByUserName(string systemCode, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopedomService/GetGroupPopedom", ReplyAction="http://tempuri.org/IPopedomService/GetGroupPopedomResponse")]
        System.Data.DataTable GetGroupPopedom(string systemCode, System.Guid groupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopedomService/HasRightModule", ReplyAction="http://tempuri.org/IPopedomService/HasRightModuleResponse")]
        bool HasRightModule(string systemCode, string moduleCode, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopedomService/GetFormFunctionRight", ReplyAction="http://tempuri.org/IPopedomService/GetFormFunctionRightResponse")]
        System.Data.DataTable GetFormFunctionRight(string systemCode, string moduleCode, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopedomService/GetGroupFormFunctionRight", ReplyAction="http://tempuri.org/IPopedomService/GetGroupFormFunctionRightResponse")]
        System.Data.DataTable GetGroupFormFunctionRight(string systemCode, string moduleCode, System.Guid groupID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPopedomServiceChannel : MCD.RLPlanning.Client.UUPPopedomService.IPopedomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PopedomServiceClient : System.ServiceModel.ClientBase<MCD.RLPlanning.Client.UUPPopedomService.IPopedomService>, MCD.RLPlanning.Client.UUPPopedomService.IPopedomService {
        
        public PopedomServiceClient() {
        }
        
        public PopedomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PopedomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PopedomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PopedomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetUserPopedomByUserName(string systemCode, string userName) {
            return base.Channel.GetUserPopedomByUserName(systemCode, userName);
        }
        
        public System.Data.DataTable GetGroupPopedom(string systemCode, System.Guid groupID) {
            return base.Channel.GetGroupPopedom(systemCode, groupID);
        }
        
        public bool HasRightModule(string systemCode, string moduleCode, string userName) {
            return base.Channel.HasRightModule(systemCode, moduleCode, userName);
        }
        
        public System.Data.DataTable GetFormFunctionRight(string systemCode, string moduleCode, string userName) {
            return base.Channel.GetFormFunctionRight(systemCode, moduleCode, userName);
        }
        
        public System.Data.DataTable GetGroupFormFunctionRight(string systemCode, string moduleCode, System.Guid groupID) {
            return base.Channel.GetGroupFormFunctionRight(systemCode, moduleCode, groupID);
        }
    }
}
